package loader

var (
	ARCH_PROMPT                              string
	PLAN_PROMPT                              string
	CODER_PROMPT                             string
	ARCH_REVIEW_PROMPT                       string
	PLAN_REVIEW_PROMPT                       string
	CODE_REVIEW_PROMPT                       string
	TECH_LEAD_FINAL_PROMPT                   string
	ARCH_FINAL_PROMPT                        string
	PRODUCT_MANAGER_PROMPT                   string
	PM_SYNTHESIZER_PROMPT                    string
	PM_EXPANSION_CLEANUP_PROMPT              string
	PM_REVIEW_PROMPT                         string
	SYSTEM_DECOMPOSITION_PROMPT              string
	SYSTEM_DECOMPOSITION_REVIEW_PROMPT       string
	DESIGN_TO_IMPLEMENT_PHRASING_PROMPT      string
	INVESTIGATION_CLASSIFIER_PROMPT          string
	INVESTIGATOR_PLANNER_PROMPT              string
	INVESTIGATOR_EXECUTOR_PROMPT             string
	SYNTHESIS_PROMPT                         string
	GAP_ANALYSIS_REVIEW_PROMPT               string
	FACT_CHECKING_REVIEW_PROMPT              string
	STRUCTURE_REVIEW_PROMPT                  string
	INVESTIGATION_PLAN_QUALITY_REVIEW_PROMPT string
	SYNTHESIS_CONSISTENCY_REVIEW_PROMPT      string
	NON_CODER_NEXT_STEPS_CLEANUP_PROMPT      string
)

func InitPrompts() {
	ARCH_PROMPT = GetPrompt(ARCH_PROMPT_ID, SchemaToExample(ARCH_SCHEMA))
	PLAN_PROMPT = GetPrompt(PLAN_PROMPT_ID, SchemaToExample(PLAN_SCHEMA))
	CODER_PROMPT = GetPrompt(CODER_PROMPT_ID, SchemaToExample(CODER_SCHEMA))
	ARCH_REVIEW_PROMPT = GetPrompt(ARCH_REVIEW_PROMPT_ID, SchemaToExample(ARCH_REVIEW_SCHEMA))
	PLAN_REVIEW_PROMPT = GetPrompt(PLAN_REVIEW_PROMPT_ID, SchemaToExample(PLAN_REVIEW_SCHEMA))
	CODE_REVIEW_PROMPT = GetPrompt(CODE_REVIEW_PROMPT_ID, SchemaToExample(CODE_REVIEW_SCHEMA))
	TECH_LEAD_FINAL_PROMPT = GetPrompt(TECH_LEAD_FINAL_PROMPT_ID, SchemaToExample(TECH_LEAD_FINAL_SCHEMA))
	ARCH_FINAL_PROMPT = GetPrompt(ARCH_FINAL_PROMPT_ID, SchemaToExample(ARCH_FINAL_SCHEMA))
	PRODUCT_MANAGER_PROMPT = GetPrompt(PRODUCT_MANAGER_PROMPT_ID, SchemaToExample(PRODUCT_MANAGER_SCHEMA))
	PM_SYNTHESIZER_PROMPT = GetPrompt(PM_SYNTHESIZER_PROMPT_ID, SchemaToExample(PM_SYNTHESIZER_SCHEMA))
	PM_EXPANSION_CLEANUP_PROMPT = GetPrompt(PM_EXPANSION_CLEANUP_PROMPT_ID, "")
	PM_REVIEW_PROMPT = GetPrompt(PM_REVIEW_PROMPT_ID, SchemaToExample(PM_REVIEW_SCHEMA))
	SYSTEM_DECOMPOSITION_PROMPT = GetPrompt(SYSTEM_DECOMPOSITION_PROMPT_ID, SchemaToExample(SYSTEM_DECOMPOSITION_SCHEMA))
	SYSTEM_DECOMPOSITION_REVIEW_PROMPT = GetPrompt(SYSTEM_DECOMPOSITION_REVIEW_PROMPT_ID, SchemaToExample(SYSTEM_DECOMPOSITION_REVIEW_SCHEMA))
	DESIGN_TO_IMPLEMENT_PHRASING_PROMPT = GetPrompt(DESIGN_TO_IMPLEMENT_PHRASING_PROMPT_ID, SchemaToExample(DESIGN_TO_IMPLEMENT_PHRASING_SCHEMA))
	INVESTIGATION_CLASSIFIER_PROMPT = GetPrompt(INVESTIGATION_CLASSIFIER_PROMPT_ID, SchemaToExample(INVESTIGATION_CLASSIFIER_SCHEMA))
	INVESTIGATOR_PLANNER_PROMPT = GetPrompt(INVESTIGATOR_PLANNER_PROMPT_ID, SchemaToExample(INVESTIGATOR_PLAN_SCHEMA))
	INVESTIGATOR_EXECUTOR_PROMPT = GetPrompt(INVESTIGATOR_EXECUTOR_PROMPT_ID, SchemaToExample(INVESTIGATOR_FINDINGS_SCHEMA))
	SYNTHESIS_PROMPT = GetPrompt(SYNTHESIS_PROMPT_ID, SchemaToExample(INVESTIGATION_REPORT_SCHEMA))
	GAP_ANALYSIS_REVIEW_PROMPT = GetPrompt(GAP_ANALYSIS_REVIEW_PROMPT_ID, SchemaToExample(GAP_ANALYSIS_REVIEW_SCHEMA))
	FACT_CHECKING_REVIEW_PROMPT = GetPrompt(FACT_CHECKING_REVIEW_PROMPT_ID, SchemaToExample(FACT_CHECKING_REVIEW_SCHEMA))
	STRUCTURE_REVIEW_PROMPT = GetPrompt(STRUCTURE_REVIEW_PROMPT_ID, SchemaToExample(STRUCTURAL_REVIEW_SCHEMA))
	INVESTIGATION_PLAN_QUALITY_REVIEW_PROMPT = GetPrompt(INVESTIGATION_PLAN_QUALITY_REVIEW_PROMPT_ID, SchemaToExample(INVESTIGATION_PLAN_QUALITY_REVIEW_SCHEMA))
	SYNTHESIS_CONSISTENCY_REVIEW_PROMPT = GetPrompt(SYNTHESIS_CONSISTENCY_REVIEW_PROMPT_ID, SchemaToExample(SYNTHESIS_CONSISTENCY_REVIEW_SCHEMA))
	NON_CODER_NEXT_STEPS_CLEANUP_PROMPT = GetPrompt(NON_CODER_NEXT_STEPS_CLEANUP_PROMPT_ID, SchemaToExample(NON_CODER_NEXT_STEPS_CLEANUP_SCHEMA))
}
