package loader

var (
	PRODUCT_MANAGER_PROMPT                   string
	PM_REVIEW_PROMPT                         string
	INVESTIGATION_CLASSIFIER_PROMPT          string
	SYSTEM_DECOMPOSITION_PROMPT              string
	SYSTEM_DECOMPOSITION_REVIEW_PROMPT       string
	ARCH_PROMPT                              string
	ARCH_REVIEW_PROMPT                       string
	PLAN_PROMPT                              string
	PLAN_REVIEW_PROMPT                       string
	CODER_PROMPT                             string
	CODE_REVIEW_PROMPT                       string
	TECH_LEAD_FINAL_PROMPT                   string
	ARCH_FINAL_PROMPT                        string
	INVESTIGATOR_PLANNER_PROMPT              string
	INVESTIGATION_PLAN_QUALITY_REVIEW_PROMPT string
	STRUCTURE_REVIEW_PROMPT                  string
	INVESTIGATOR_EXECUTOR_PROMPT             string
	FACT_CHECKING_REVIEW_PROMPT              string
	GAP_ANALYSIS_REVIEW_PROMPT               string
	SYNTHESIS_PROMPT                         string
	SYNTHESIS_CONSISTENCY_REVIEW_PROMPT      string
)

// InitPrompts loads and renders every content-agent role prompt template.
// Decision-agent prompts (workflow_driver, loop_decider) are rendered by the
// orchestrator package with their JSON schema and example response.
func InitPrompts() {
	PRODUCT_MANAGER_PROMPT = GetPrompt(PRODUCT_MANAGER_PROMPT_ID)
	PM_REVIEW_PROMPT = GetPrompt(PM_REVIEW_PROMPT_ID)
	INVESTIGATION_CLASSIFIER_PROMPT = GetPrompt(INVESTIGATION_CLASSIFIER_PROMPT_ID)
	SYSTEM_DECOMPOSITION_PROMPT = GetPrompt(SYSTEM_DECOMPOSITION_PROMPT_ID)
	SYSTEM_DECOMPOSITION_REVIEW_PROMPT = GetPrompt(SYSTEM_DECOMPOSITION_REVIEW_PROMPT_ID)
	ARCH_PROMPT = GetPrompt(ARCH_PROMPT_ID)
	ARCH_REVIEW_PROMPT = GetPrompt(ARCH_REVIEW_PROMPT_ID)
	PLAN_PROMPT = GetPrompt(PLAN_PROMPT_ID)
	PLAN_REVIEW_PROMPT = GetPrompt(PLAN_REVIEW_PROMPT_ID)
	CODER_PROMPT = GetPrompt(CODER_PROMPT_ID)
	CODE_REVIEW_PROMPT = GetPrompt(CODE_REVIEW_PROMPT_ID)
	TECH_LEAD_FINAL_PROMPT = GetPrompt(TECH_LEAD_FINAL_PROMPT_ID)
	ARCH_FINAL_PROMPT = GetPrompt(ARCH_FINAL_PROMPT_ID)
	INVESTIGATOR_PLANNER_PROMPT = GetPrompt(INVESTIGATOR_PLANNER_PROMPT_ID)
	INVESTIGATION_PLAN_QUALITY_REVIEW_PROMPT = GetPrompt(INVESTIGATION_PLAN_QUALITY_REVIEW_PROMPT_ID)
	STRUCTURE_REVIEW_PROMPT = GetPrompt(STRUCTURE_REVIEW_PROMPT_ID)
	INVESTIGATOR_EXECUTOR_PROMPT = GetPrompt(INVESTIGATOR_EXECUTOR_PROMPT_ID)
	FACT_CHECKING_REVIEW_PROMPT = GetPrompt(FACT_CHECKING_REVIEW_PROMPT_ID)
	GAP_ANALYSIS_REVIEW_PROMPT = GetPrompt(GAP_ANALYSIS_REVIEW_PROMPT_ID)
	SYNTHESIS_PROMPT = GetPrompt(SYNTHESIS_PROMPT_ID)
	SYNTHESIS_CONSISTENCY_REVIEW_PROMPT = GetPrompt(SYNTHESIS_CONSISTENCY_REVIEW_PROMPT_ID)
}
